-- 1. Create the QA Defaults table
CREATE TABLE IF NOT EXISTS public.qa_defaults (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id INTEGER NOT NULL,
    group_name TEXT NOT NULL,
    response_value TEXT NOT NULL, -- 'yes', 'no', or the index '0', '1', '2' for dropdowns
    feedback_text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    -- Ensure we don't have duplicate entries for the same group/item/response
    UNIQUE(group_name, item_id, response_value)
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.qa_defaults ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy to allow public (anonymous) read access
-- This allows your bookmarklet to fetch data without a complex login
DROP POLICY IF EXISTS "Enable read access for all users" ON public.qa_defaults;
CREATE POLICY "Enable read access for all users" 
ON public.qa_defaults 
FOR SELECT 
USING (true);

-- 4. Insert Initial Data
-- Note: 'yes' always refers to the LEFT button in your UI, 'no' refers to the RIGHT button.
-- For dropdowns, the response_value is the INDEX (0, 1, 2...).

INSERT INTO public.qa_defaults (item_id, group_name, response_value, feedback_text) VALUES
-- AQM GROUP (Items 1-10)
(1, 'AQM', 'yes', 'Agent provided a clear branding greeting.'),
(1, 'AQM', 'no', 'Agent failed to introduce themselves or the brand.'),
(2, 'AQM', 'yes', 'Customer name was correctly confirmed.'),
(2, 'AQM', 'no', 'Agent did not verify the customer name.'),
(3, 'AQM', 'yes', ''),
(3, 'AQM', 'no', 'Agent failed to confirm the business name.'),
(4, 'AQM', 'yes', ''),
(4, 'AQM', 'no', 'No callback number was verified.'),
(5, 'AQM', 'yes', ''),
(5, 'AQM', 'no', 'Closing was abrupt or missing.'),
(6, 'AQM', 'yes', 'Agent demonstrated active listening throughout.'), -- 'yes' is LEFT (No Poor Listening)
(6, 'AQM', 'no', 'Agent repeatedly interrupted the customer.'),        -- 'no' is RIGHT (Yes Poor Listening)
(7, 'AQM', 'yes', ''),
(7, 'AQM', 'no', 'Tone was unprofessional or disinterested.'),
(8, 'AQM', 'yes', 'Agent maintained control of the call.'),            -- 'yes' is LEFT (No Poor Control)
(8, 'AQM', 'no', 'Call was disorganized with excessive dead air.'),     -- 'no' is RIGHT (Yes Poor Control)
(9, 'AQM', 'yes', 'Agent expressed genuine empathy.'),
(9, 'AQM', 'no', 'Agent was robotic or lacked empathy.'),
(10, 'AQM', 'yes', ''),
(10, 'AQM', 'no', 'Solution was not confirmed with the user.'),

-- CASE MANAGEMENT GROUP (Select items)
(1, 'Case Management', 'yes', 'Resolution provided was accurate.'),
(1, 'Case Management', 'no', 'Incorrect resolution offered.'),
(13, 'Case Management', '2', 'No expert assistance was required.'), -- Index 2 is "N/A"
(14, 'Case Management', '0', 'Case was staged correctly.'),          -- Index 0 is "No - staged correctly"
(16, 'Case Management', '2', 'Customer was neutral at the start.'),  -- Index 2 is "Neutral"
(17, 'Case Management', '2', 'Customer remained neutral at the end.'),-- Index 2 is "Neutral"
(19, 'Case Management', '6', 'Issue was a simple task for Care.'),   -- Index 6 is "Simple Task..."
(22, 'Case Management', '6', 'N/A')                                  -- Index 6 is "N/A"
ON CONFLICT (group_name, item_id, response_value) 
DO UPDATE SET feedback_text = EXCLUDED.feedback_text;
