-- 1. Add item_name column to qa_defaults for better readability
ALTER TABLE public.qa_defaults 
ADD COLUMN IF NOT EXISTS item_name TEXT;

-- Update existing rows with names (Best effort based on IDs)
UPDATE public.qa_defaults SET item_name = 'Greeting' WHERE item_id = 1 AND group_name = 'AQM';
UPDATE public.qa_defaults SET item_name = 'Cx Name' WHERE item_id = 2 AND group_name = 'AQM';
UPDATE public.qa_defaults SET item_name = 'Business Name' WHERE item_id = 3 AND group_name = 'AQM';
UPDATE public.qa_defaults SET item_name = 'Callback' WHERE item_id = 4 AND group_name = 'AQM';
UPDATE public.qa_defaults SET item_name = 'Closing' WHERE item_id = 5 AND group_name = 'AQM';
UPDATE public.qa_defaults SET item_name = 'Poor Listening' WHERE item_id = 6 AND group_name = 'AQM';
UPDATE public.qa_defaults SET item_name = 'Appropriate Tone' WHERE item_id = 7 AND group_name = 'AQM';
UPDATE public.qa_defaults SET item_name = 'Poor Call Control' WHERE item_id = 8 AND group_name = 'AQM';
UPDATE public.qa_defaults SET item_name = 'Empathy' WHERE item_id = 9 AND group_name = 'AQM';
UPDATE public.qa_defaults SET item_name = 'Confirm Solution' WHERE item_id = 10 AND group_name = 'AQM';

-- Case Management Names
UPDATE public.qa_defaults SET item_name = 'Resolution' WHERE item_id = 1 AND group_name = 'Case Management';
UPDATE public.qa_defaults SET item_name = 'Expert Needed' WHERE item_id = 13 AND group_name = 'Case Management';
UPDATE public.qa_defaults SET item_name = 'Incorrect Case Staging' WHERE item_id = 14 AND group_name = 'Case Management';
UPDATE public.qa_defaults SET item_name = 'Temp Start' WHERE item_id = 16 AND group_name = 'Case Management';
UPDATE public.qa_defaults SET item_name = 'Temp End' WHERE item_id = 17 AND group_name = 'Case Management';
UPDATE public.qa_defaults SET item_name = 'Complexity' WHERE item_id = 19 AND group_name = 'Case Management';
UPDATE public.qa_defaults SET item_name = 'Root Cause' WHERE item_id = 22 AND group_name = 'Case Management';


-- 2. Create the QA Tags table (Sub-reasons)
CREATE TABLE IF NOT EXISTS public.qa_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id INTEGER NOT NULL,
    group_name TEXT NOT NULL,
    item_name TEXT, -- Added for convenience as requested
    response_value TEXT NOT NULL, -- The parent response ('yes', 'no', '0', etc.)
    tag_label TEXT NOT NULL, -- The text on the badge button (e.g. 'No Branding')
    tag_feedback TEXT NOT NULL, -- The feedback text to append if selected
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Enable Security for Tags
ALTER TABLE public.qa_tags ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable read access for all users" ON public.qa_tags;
CREATE POLICY "Enable read access for all users" 
ON public.qa_tags 
FOR SELECT 
USING (true);

-- 4. Populate Tags (First 10 Items - AQM)

-- Item 1: Greeting (No)
INSERT INTO public.qa_tags (item_id, group_name, item_name, response_value, tag_label, tag_feedback) VALUES
(1, 'AQM', 'Greeting', 'no', 'No Branding', 'Agent failed to provide the branding toast.'),
(1, 'AQM', 'Greeting', 'no', 'No Name', 'Agent did not introduce themselves.'),
(1, 'AQM', 'Greeting', 'no', 'Too Fast', 'Greeting was rushed and unclear.');

-- Item 2: Cx Name (No)
INSERT INTO public.qa_tags (item_id, group_name, item_name, response_value, tag_label, tag_feedback) VALUES
(2, 'AQM', 'Cx Name', 'no', 'Not Asked', 'Agent did not ask for the customer''s name.'),
(2, 'AQM', 'Cx Name', 'no', 'Not Verified', 'Agent did not verify the spelling or pronunciation of the name.');

-- Item 3: Business Name (No)
INSERT INTO public.qa_tags (item_id, group_name, item_name, response_value, tag_label, tag_feedback) VALUES
(3, 'AQM', 'Business Name', 'no', 'Not Confirmed', 'Business name was not confirmed.'),
(3, 'AQM', 'Business Name', 'no', 'Incorrect', 'Agent referenced the wrong business name.');

-- Item 4: Callback (No)
INSERT INTO public.qa_tags (item_id, group_name, item_name, response_value, tag_label, tag_feedback) VALUES
(4, 'AQM', 'Callback', 'no', 'Not Asked', 'Callback number was not requested.'),
(4, 'AQM', 'Callback', 'no', 'Not Read Back', 'Agent failed to read back the callback number for verification.');

-- Item 5: Closing (No)
INSERT INTO public.qa_tags (item_id, group_name, item_name, response_value, tag_label, tag_feedback) VALUES
(5, 'AQM', 'Closing', 'no', 'Abrupt', 'Call ended abruptly without proper closing.'),
(5, 'AQM', 'Closing', 'no', 'No Branding', 'Closing branding was missing.');

-- Item 6: Poor Listening (Yes/Right - Reversed item)
-- Note: Logic in JS sends 'no' for the Right button if reverseButtons is true. 
-- Wait, let's check JS. 
-- JS: btnYes (Left) -> "no" (Text: No), sel="yes"
-- JS: btnNo (Right) -> "yes" (Text: Yes), sel="no"
-- The logic in qa_defaults uses 'no' for the "Bad" outcome (Right button).
-- So we attach tags to 'no'.
INSERT INTO public.qa_tags (item_id, group_name, item_name, response_value, tag_label, tag_feedback) VALUES
(6, 'AQM', 'Poor Listening', 'no', 'Interrupting', 'Agent repeatedly interrupted the customer.'),
(6, 'AQM', 'Poor Listening', 'no', 'Talking Over', 'Agent talked over the customer.'),
(6, 'AQM', 'Poor Listening', 'no', 'Ignored Q', 'Agent ignored a direct question from the customer.');

-- Item 7: Appropriate Tone (No)
INSERT INTO public.qa_tags (item_id, group_name, item_name, response_value, tag_label, tag_feedback) VALUES
(7, 'AQM', 'Appropriate Tone', 'no', 'Monotone', 'Agent sounded monotone and disinterested.'),
(7, 'AQM', 'Appropriate Tone', 'no', 'Rude', 'Agent tone was perceived as rude or impatient.');

-- Item 8: Poor Call Control (Yes/Right - Reversed)
-- Same logic as #6, 'no' is the Right button (Bad outcome)
INSERT INTO public.qa_tags (item_id, group_name, item_name, response_value, tag_label, tag_feedback) VALUES
(8, 'AQM', 'Poor Call Control', 'no', 'Dead Air', 'Excessive dead air during the call.'),
(8, 'AQM', 'Poor Call Control', 'no', 'Disorganized', 'Troubleshooting steps were disorganized.');

-- Item 9: Empathy (No)
INSERT INTO public.qa_tags (item_id, group_name, item_name, response_value, tag_label, tag_feedback) VALUES
(9, 'AQM', 'Empathy', 'no', 'Robotic', 'Responses were scripted and robotic.'),
(9, 'AQM', 'Empathy', 'no', 'Dismissive', 'Agent was dismissive of the customer''s frustration.');

-- Item 10: Confirm Solution (No)
INSERT INTO public.qa_tags (item_id, group_name, item_name, response_value, tag_label, tag_feedback) VALUES
(10, 'AQM', 'Confirm Solution', 'no', 'No Recap', 'Agent failed to recap the solution.'),
(10, 'AQM', 'Confirm Solution', 'no', 'No Agreement', 'Did not confirm with customer if the solution worked.');
